## Pandas Series 
### Creating Series

In [6]:
import pandas as pd

In [7]:
labels = ['a','b','c']
my_list = [10, 20, 30]
my_dictionary = {'a':10, 'b':20, 'c':30}

In [8]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(my_dictionary)

a    10
b    20
c    30
dtype: int64

## DataFrames

In [10]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df2 = pd.DataFrame(data_list)
columns = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [13]:
df2['Designation'] = ['Engineer', 'Doctor', 'Scientist', 'Mathematician']

In [14]:
df2

    Name  Age      City  Salary    Designation
0   John   28  New York   65000       Engineer
1   Anna   34     Paris   70000         Doctor
2  Peter   29    Berlin   62000      Scientist
3  Linda   42    London   85000  Mathematician

In [15]:
df2.drop(0,axis = 0)

    Name  Age    City  Salary    Designation
1   Anna   34   Paris   70000         Doctor
2  Peter   29  Berlin   62000      Scientist
3  Linda   42  London   85000  Mathematician

In [16]:
df2

    Name  Age      City  Salary    Designation
0   John   28  New York   65000       Engineer
1   Anna   34     Paris   70000         Doctor
2  Peter   29    Berlin   62000      Scientist
3  Linda   42    London   85000  Mathematician

In [17]:
df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [18]:
#condition is to select the age above 30 and city of paris
df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000      Doctor

## Missing Data

In [19]:
import numpy as np
import pandas as pd

In [20]:
data2 = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df3 = pd.DataFrame(data2)
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [21]:
df3.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [22]:
df3.dropna(thresh = 2)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [23]:
df3.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [24]:
values = {'A':10, 'B':20, 'C':30, 'D':40}
df3.fillna(value = values)

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  40.0
2  10.0  3   3.0  40.0
3   4.0  4  30.0  40.0
4   5.0  5  30.0   5.0

In [25]:
df3.fillna(df3.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

## Merging Joining and Catenation

In [26]:
import pandas as pd

# DataFrame 1: Employee information
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [27]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [28]:
pd.merge(employees,salaries,on='employee_id',how = 'inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [29]:
import pandas as pd

df4 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df5 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [30]:
pd.concat([df4,df5],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [31]:
import pandas as pd

df6 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df7 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [32]:
df7.join(df6,how = 'outer')

   score     name
1    NaN    Alice
2   85.0      Bob
3   90.0  Charlie
4   75.0      NaN

## GroupBy and Aggregation

In [33]:
import pandas as pd

data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df8 = pd.DataFrame(data)

In [34]:
df8

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [35]:
#groupby category and calculate the sum of sales
df8.groupby('Category')['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [36]:
df8.groupby('Store')['Sales'].sum()

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [37]:
df8.groupby(['Category','Store'])['Sales'].sum()

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [38]:
#Aggregation
df8['Sales'].mean()

np.float64(187.5)

In [39]:
df8['Sales'].agg(['mean','max','min','std','median','sum','count'])

mean       187.500000
max        300.000000
min        100.000000
std         66.062741
median     190.000000
sum       1500.000000
count        8.000000
Name: Sales, dtype: float64

## Pivot Tables

In [40]:
import pandas as pd
import numpy as np

data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [41]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    359     79   John  January      Q1
1  2023-01-02       B   West    990     60   Mary  January      Q1
2  2023-01-03       C  North    376     42    Bob  January      Q1
3  2023-01-04       D  South    675     95  Alice  January      Q1
4  2023-01-05       A   East    153     19   John  January      Q1
5  2023-01-06       B   West    236     65   Mary  January      Q1
6  2023-01-07       C  North    360     65    Bob  January      Q1
7  2023-01-08       D  South    232     15  Alice  January      Q1
8  2023-01-09       A   East    375     49   John  January      Q1
9  2023-01-10       B   West    709     41   Mary  January      Q1
10 2023-01-11       C  North    977     14    Bob  January      Q1
11 2023-01-12       D  South    709     39  Alice  January      Q1
12 2023-01-13       A   East    325     53   John  January      Q1
13 2023-01-14       B   West    754     43   Mary  January      Q1
14 2023-01-15       C  North    668     90    Bob  January      Q1
15 2023-01-16       D  South    793     89  Alice  January      Q1
16 2023-01-17       A   East    286     15   John  January      Q1
17 2023-01-18       B   West    856     89   Mary  January      Q1
18 2023-01-19       C  North    770     63    Bob  January      Q1
19 2023-01-20       D  South    909     57  Alice  January      Q1

In [42]:
pd.pivot_table(df,values = ['Sales','Units'], index = 'Region', columns= 'Product', aggfunc= 'median')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     325.0    NaN    NaN    NaN  49.0   NaN   NaN   NaN
North      NaN    NaN  668.0    NaN   NaN   NaN  63.0   NaN
South      NaN    NaN    NaN  709.0   NaN   NaN   NaN  57.0
West       NaN  754.0    NaN    NaN   NaN  60.0   NaN   NaN

In [43]:
#crosstabs
pd.crosstab(df['Sales'],df['Units'])

Units  14  15  19  39  41  42  43  49  53  57  60  63  65  79  89  90  95
Sales
153     0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0
232     0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
236     0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0
286     0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
325     0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0
359     0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0
360     0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0
375     0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0
376     0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0
668     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0
675     0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
709     0   0   0   1   1   0   0   0   0   0   0   0   0   0   0   0   0
754     0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0
770     0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0
793     0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0
856     0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0
909     0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0
977     1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
990     0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0

## Operations

In [44]:
import pandas as pd

df9 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df9

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [45]:
df9.A

0    1
1    2
2    3
3    4
4    5
Name: A, dtype: int64

In [46]:
df9.shape

(5, 3)

In [47]:
df9.columns

Index(['A', 'B', 'C'], dtype='object')

In [48]:
df9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [49]:
df9.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [50]:
df9['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

DataFrames applying functions

In [51]:
df9

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [52]:
def square(x):
   return x**2

In [53]:
df9['D'] = df9['B'].apply(square)

In [54]:
df9

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500